version: "3.2"
services:
    backend:
        build: .
        volumes: 
            - ./:/opt/app:rw
            - ./nodemodule:/opt/app/node_modules:rw
        environment:
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: docker2
        ports: 
            - 5050:3000
        networks: 
            - backend_srv
        depends_on:
           - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker2
        networks:
            - backend_srv
    adminer:
        image: adminer
        restart: always
        ports: 
            - 8085:8080
        networks: 
            - backend_srv
networks: 
    backend_srv:
        driver: "bridge"